[package]
name = "turtle-build"
description = "The Ninja build system clone written in Rust"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
repository = "https://github.com/raviqqe/turtle"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = true

[[bin]]
name = "turtle"
path = "src/main.rs"

[dependencies]
async-recursion = "1"
clap = { version = "3", features = ["derive"] }
combine = "4"
futures = "0.3"
num_cpus = "1"
once_cell = "1"
petgraph = "0.6"
pretty_assertions = "1"
regex = "1"
sled = "0.34"
tempfile = "3"
tokio = { "version" = "1", features = ["full"] }
