name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  benchmark:
    strategy:
      matrix:
        benchmark:
          - simple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: raviqqe/enable-homebrew@main
      - run: brew install ninja
      - run: cargo install --path . --locked
      - run: benchmark/${{ matrix.benchmark }}/main.sh
