name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: cargo fmt -- --check
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{md,rs,sh,toml}"
  unused_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - run: tools/unused_dependencies.sh
      - run: |
          rustup install nightly
          rustup run nightly cargo install cargo-udeps
          cargo +nightly udeps
