name: test
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: tools/build.sh
      - run: git diff --exit-code
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: target/release/turtle*
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
  integration_test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: target/release
      - run: chmod +x target/release/turtle*
      - run: tools/integration_test.sh
  integration_test_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO Enable this on Windows.
          # - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: aminya/setup-cpp@v1
        with:
          ninja: true
      - run: mkdir -p target/release
      - run: cp tools/turtle.sh target/release/turtle
      - run: rm -r features/turtle
      - run: tools/integration_test.sh
